BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "conjunction_table" (
	"disaster_id"	TEXT NOT NULL UNIQUE,
	"time_id"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("disaster_id"),
	FOREIGN KEY("time_id") REFERENCES "conjunction_table"("time_id") ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "natural_disasters" (
	"Event Disaster ID"	TEXT NOT NULL UNIQUE,
	"Event Name"	TEXT NOT NULL,
	"Countries affected"	TEXT,
	"Event Disaster Type"	TEXT,
	"Event Death toll (Estimate)"	INTEGER,
	PRIMARY KEY("Event Disaster ID")
);
CREATE TABLE IF NOT EXISTS "time" (
	"time_id"	TEXT NOT NULL UNIQUE,
	"Date (From)"	TEXT NOT NULL,
	"Date (To)"	TEXT,
	"Note"	TEXT,
	"disaster_id"	TEXT UNIQUE,
	PRIMARY KEY("time_id"),
	FOREIGN KEY("disaster_id") REFERENCES "natural_disasters"("Event Disaster ID") ON UPDATE CASCADE
);
CREATE TABLE IF NOT EXISTS "top_list_of_natural_disasters" (
	"Top Event ID"	TEXT NOT NULL UNIQUE,
	"Top Event Death toll (Highest estimate)"	INTEGER NOT NULL,
	"Top Event Name"	TEXT NOT NULL,
	"Top Event Location"	TEXT,
	"Top Event Date"	TEXT,
	"Top Event Note"	TEXT,
	"disaster_id"	TEXT,
	PRIMARY KEY("Top Event ID"),
	FOREIGN KEY("disaster_id") REFERENCES "natural_disasters"("Event Disaster ID") ON UPDATE CASCADE
);
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_1','time_1');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_2','time_2');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_3','time_3');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_4','time_4');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_5','time_5');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_6','time_6');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_7','time_7');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_8','time_8');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_9','time_9');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_10','time_10');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_11','time_11');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_12','time_12');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_13','time_13');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_14','time_14');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_15','time_15');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_16','time_16');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_17','time_17');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_18','time_18');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_19','time_19');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_20','time_20');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_21','time_21');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_22','time_22');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_23','time_23');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_24','time_24');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_25','time_25');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_26','time_26');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_27','time_27');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_28','time_28');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_29','time_29');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_30','time_30');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_31','time_31');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_32','time_32');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_33','time_33');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_34','time_34');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_35','time_35');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_36','time_36');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_37','time_37');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_38','time_38');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_39','time_39');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_40','time_40');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_41','time_41');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_42','time_42');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_43','time_43');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_44','time_44');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_45','time_45');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_46','time_46');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_47','time_47');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_48','time_48');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_49','time_49');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_50','time_50');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_51','time_51');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_52','time_52');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_53','time_53');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_54','time_54');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_55','time_55');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_56','time_56');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_57','time_57');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_58','time_58');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_59','time_59');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_60','time_60');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_61','time_61');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_62','time_62');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_63','time_63');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_64','time_64');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_65','time_65');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_66','time_66');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_67','time_67');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_68','time_68');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_69','time_69');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_70','time_70');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_71','time_71');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_72','time_72');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_73','time_73');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_74','time_74');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_75','time_75');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_76','time_76');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_77','time_77');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_78','time_78');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_79','time_79');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_80','time_80');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_81','time_81');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_82','time_82');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_83','time_83');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_84','time_84');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_85','time_85');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_86','time_86');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_87','time_87');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_88','time_88');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_89','time_89');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_90','time_90');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_91','time_91');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_92','time_92');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_93','time_93');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_94','time_94');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_95','time_95');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_96','time_96');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_97','time_97');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_98','time_98');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_99','time_99');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_100','time_100');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_101','time_101');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_102','time_102');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_103','time_103');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_104','time_104');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_105','time_105');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_106','time_106');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_107','time_107');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_108','time_108');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_109','time_109');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_110','time_110');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_111','time_111');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_112','time_112');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_113','time_113');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_114','time_114');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_115','time_115');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_116','time_116');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_117','time_117');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_118','time_118');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_119','time_119');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_120','time_120');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_121','time_121');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_122','time_122');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_123','time_123');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_124','time_124');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_125','time_125');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_126','time_126');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_127','time_127');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_128','time_128');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_129','time_129');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_130','time_130');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_131','time_131');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_132','time_132');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_133','time_133');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_134','time_134');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_135','time_135');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_136','time_136');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_137','time_137');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_138','time_138');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_139','time_139');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_140','time_140');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_141','time_141');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_142','time_142');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_143','time_143');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_144','time_144');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_145','time_145');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_146','time_146');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_147','time_147');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_148','time_148');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_149','time_149');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_150','time_150');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_151','time_151');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_152','time_152');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_153','time_153');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_154','time_154');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_155','time_155');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_156','time_156');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_157','time_157');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_158','time_158');
INSERT INTO "conjunction_table" ("disaster_id","time_id") VALUES ('disaster_159','time_159');
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_1','1917 Guatemala earthquakes','Guatemala','Earthquake',2650);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_2','1918 Shantou earthquake','China','Earthquake',1000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_3','1918 Shantou earthquake','Taiwan','Earthquake',1000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_4','1918 Shantou earthquake','Philippines','Earthquake',1000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_5','1919 Florida Keys hurricane','United States','Tropical cyclone',772);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_6','1920 Haiyuan earthquake','Mongolia','Earthquake',236700);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_7','1920 Haiyuan earthquake','China','Earthquake',236700);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_8','September 1921 San Antonio floods','United States','Flood',215);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_9','1922 Swatow typhoon','Philippines','Tropical cyclone',75000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_10','1922 Swatow typhoon','China','Tropical cyclone',75000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_11','1923 Great Kantō earthquake','Japan','Earthquake',142800);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_12','1924 India floods','India','Flood',1000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_13','1925 Dali earthquake','China','Earthquake',5000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_14','1926 Havana–Bermuda hurricane','Cuba','Tropical cyclone',709);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_15','1926 Havana–Bermuda hurricane','United States','Tropical cyclone',709);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_16','1926 Havana–Bermuda hurricane','Bahamas','Tropical cyclone',709);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_17','1926 Havana–Bermuda hurricane','Bermuda','Tropical cyclone',709);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_18','1927 Gulang earthquake','China','Earthquake',40900);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_19','1927 Gulang earthquake','Tibet','Earthquake',40900);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_20','1928 Okeechobee hurricane','United States','Tropical cyclone',4112);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_21','1928 Okeechobee hurricane','Puerto Rico','Tropical cyclone',4112);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_22','1928 Okeechobee hurricane','Guadeloupe','Tropical cyclone',4112);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_23','1928 Okeechobee hurricane','Bahamas','Tropical cyclone',4112);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_24','1928 Okeechobee hurricane','Dominica','Tropical cyclone',4112);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_25','1929 Kopet Dag earthquake','Iran','Earthquake',3529);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_26','1929 Kopet Dag earthquake','Turkmenistan','Earthquake',3529);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_27','1930 San Zenón hurricane','Dominican Republic','Tropical cyclone',3529);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_28','1931 China floods','China','Flood',2211250);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_29','1932 Cuba hurricane','Cayman Islands','Tropical cyclone',3103);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_30','1932 Cuba hurricane','Cuba','Tropical cyclone',3103);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_31','1933 Diexi earthquake','China','Earthquake',8083);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_32','1934 Nepal–India earthquake','Nepal','Earthquake',11350);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_33','1934 Nepal–India earthquake','India','Earthquake',11350);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_34','1935 Quetta earthquake','Pakistan','Earthquake',45000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_35','1936 North American heat wave','United States','Heat wave',5000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_36','1936 North American heat wave','Canada','Heat wave',5000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_37','1937 Great Hong Kong typhoon','China','Tropical cyclone',11021);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_38','1938 Hanshin flood','Japan','Flood',715);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_39','1939 Erzincan earthquake','Turkey','Earthquake',32834);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_40','1940 Vrancea earthquake','Romania','Earthquake',1000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_41','1941 Jabal Razih earthquake','Yemen','Earthquake',1200);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_42','1942 West Bengal cyclone','India','Tropical cyclone',61000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_43','1943 Tosya–Ladik earthquake','Turkey','Earthquake',4020);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_44','1944 San Juan earthquake','Argentina','Earthquake',10000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_45','1945 Balochistan earthquake','India','Earthquake',4000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_46','1945 Balochistan earthquake','Pakistan','Earthquake',4000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_47','1946 Dominican Republic earthquake','Dominican Republic','Earthquake',2550);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_48','Typhoon Kathleen','Japan','Tropical cyclone',1077);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_49','1948 Ashgabat earthquake','Russia','Earthquake',60000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_50','1948 Ashgabat earthquake','Iran','Earthquake',60000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_51','1949 Eastern Guatemalan floods','Guatemala','Flood',4000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_52','1950 Pakistan flood','Pakistan','Flood',2910);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_53','1951 Manchuria flood','China','Flood',4800);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_54','1952 Severo-Kurilsk earthquake','Russia','Earthquake',2336);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_55','1953 Northern Kyushu flood','Japan','Flood',771);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_56','1954 Yangtze floods','China','Flood',33000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_57','Hurricane Janet','Lesser Antilles','Tropical cyclone',1023);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_58','Hurricane Janet','Mexico','Tropical cyclone',1023);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_59','Typhoon Wanda (1956)','China','Typhoon',4935);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_60','1957 Hamadan Province earthquake','Iran','Earthquake',1200);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_61','Typhoon Ida (1958)','Japan','Tropical cyclone',1269);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_62','Typhoon Vera',NULL,'Typhoon','5,000');
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_63','Severe Cyclonic Storm Ten','Bangladesh','Tropical cyclone',14174);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_64','Cyclone Winnie',NULL,'Tropical cyclone',11468);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_65','1962 Buin Zahra earthquake','Iran','Earthquake',12225);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_66','May 1963 East Pakistan II cyclone','Bangladesh','Tropical cyclone',22000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_67','Tropical Storm Joan (1964)','Vietnam','Tropical Storm',7000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_68','1965 Bengal cyclones','Bangladesh','Tropical cyclone',47000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_69','1965 Bengal cyclones','Bangladesh','Tropical cyclone',47000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_70','1966 Varto earthquake','Turkey','Earthquake',2697);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_71','1967 Pacific typhoon season','Asia','Typhoon',934);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_72','1968 Dasht-e Bayaz and Ferdows earthquakes','Iran','Earthquake',15000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_73','1969 Yangjiang earthquake','China','Earthquake',3000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_74','1970 Bhola cyclone','Bangladesh','Tropical cyclone',300000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_75','Hanoi and Red River Delta flood','North Vietnam','Flood',100000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_76','1972 Qir earthquake','Iran','Earthquake',5374);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_77','1973 Luhuo earthquake','China','Earthquake',2190);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_78','Hurricane Fifi–Orlene','Honduras','Tropical cyclone',8210);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_79','Hurricane Fifi–Orlene','Nicaragua','Tropical cyclone',8210);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_80','Hurricane Fifi–Orlene','El Salvador','Tropical cyclone',8210);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_81','Hurricane Fifi–Orlene','Guatemala','Tropical cyclone',8210);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_82','Hurricane Fifi–Orlene','Belize','Tropical cyclone',8210);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_83','Hurricane Fifi–Orlene','Mexico','Tropical cyclone',8210);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_84','Typhoon Nina (1975)','China','Typhoon',229000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_85','1976 Tangshan earthquake',NULL,'Earthquake',448885);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_86','1977 Andhra Pradesh cyclone','India','Tropical cyclone',30000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_87','1978 Tabas earthquake','Iran','Earthquake',20000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_88','Hurricane David','Dominican Republic','Tropical cyclone',2069);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_89','Hurricane David','Dominica','Tropical cyclone',2069);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_90','1980 El Asnam earthquake','Algeria','Earthquake',5000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_91','1981 Golbaf earthquake','Iran','Earthquake',3000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_92','1982 North Yemen earthquake','Yemen','Earthquake',2800);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_93','1983 Erzurum earthquake','Turkey','Earthquake',1342);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_94','Typhoon Ike','Philippines','Tropical cyclone',1474);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_95','Armero tragedy','Colombia','Volcanic eruption',23000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_96','Lake Nyos disaster','Cameroon','Limnic eruption',1746);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_97','1987 Ecuador earthquakes','Ecuador','Earthquake',5000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_98','1988 Armenian earthquake','Armenia','Earthquake',25000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_99','1989 Sichuan flood','China','Flood',3814);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_100','1990 Manjil–Rudbar earthquake','Iran','Earthquake',50000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_101','1991 Bangladesh cyclone','Bangladesh','Tropical cyclone',138866);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_102','1992 Flores earthquake and tsunami','Indonesia','Earthquake',2500);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_103','1992 Flores earthquake and tsunami','Indonesia','Tsunami',2500);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_104','1993 Latur earthquake','India','Earthquake',9748);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_105','1994 Páez River earthquake','Colombia','Earthquake',1100);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_106','Great Hanshin earthquake','Japan','Earthquake',6434);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_107','1996 Andhra Pradesh cyclone','India','Tropical cyclone',1077);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_108','Tropical Storm Linda (1997)','Vietnam','Tropical cyclone',3123);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_109','Tropical Storm Linda (1997)','Vietnam','Flood',3123);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_110','Tropical Storm Linda (1997)','Thailand','Tropical cyclone',3123);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_111','Tropical Storm Linda (1997)','Thailand','Flood',3123);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_112','Hurricane Mitch','Honduras','Tropical cyclone',11374);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_113','Hurricane Mitch','Nicaragua','Tropical cyclone',11374);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_114','Hurricane Mitch','El Salvador','Tropical cyclone',11374);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_115','Hurricane Mitch','Guatemala','Tropical cyclone',11374);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_116','Hurricane Mitch','Belize','Tropical cyclone',11374);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_117','Hurricane Mitch','Mexico','Tropical cyclone',11374);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_118','1999 İzmit earthquake','Turkey','Earthquake',17127);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_119','2000 Mozambique flood','Mozambique','Flood',800);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_120','2001 Gujarat earthquake','India','Earthquake',20085);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_121','2002 Indian heat wave',NULL,'Heat wave',1030);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_122','2003 European heat wave','Europe','Heat wave',72000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_123','2004 Indian Ocean earthquake','Indonesia','Earthquake',227898);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_124','2004 Indian Ocean earthquake','Sri Lanka','Earthquake',227898);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_125','2004 Indian Ocean earthquake','India','Earthquake',227898);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_126','2004 Indian Ocean earthquake','Thailand','Earthquake',227898);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_127','2004 Indian Ocean earthquake','Somalia','Earthquake',227898);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_128','2004 Indian Ocean tsunami','Indonesia','Tsunami',227898);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_129','2004 Indian Ocean tsunami','Sri Lanka','Tsunami',227898);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_130','2004 Indian Ocean tsunami','India','Tsunami',227898);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_131','2004 Indian Ocean tsunami','Thailand','Tsunami',227898);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_132','2004 Indian Ocean tsunami','Somalia','Tsunami',227898);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_133','2005 Kashmir earthquake','India','Earthquake',87351);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_134','2005 Kashmir earthquake','Pakistan','Earthquake',87351);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_135','2006 Yogyakarta earthquake','Indonesia','Earthquake',5782);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_136','Cyclone Sidr','Bangladesh','Tropical cyclone',15000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_137','Cyclone Sidr','India','Tropical cyclone',15000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_138','Cyclone Nargis','Myanmar','Tropical cyclone',138373);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_139','2009 Sumatra earthquakes','Indonesia','Earthquake',1115);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_140','2010 Haiti earthquake','Haiti','Earthquake',208000);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_141','2011 Tōhoku earthquake and tsunami','Japan','Earthquake',19749);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_142','2011 Tōhoku earthquake and tsunami','Japan','Tsunami',19749);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_143','Typhoon Bopha','Philippines','Typhoon',1901);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_144','Typhoon Haiyan','Philippines','Typhoon',6340);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_145','Typhoon Haiyan','Vietnam','Typhoon',6340);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_146','Typhoon Haiyan','China','Typhoon',6340);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_147','2014 Badakhshan mudslides','Afghanistan','Landslide',2700);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_148','April 2015 Nepal earthquake','Nepal','Earthquake',8964);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_149','April 2015 Nepal earthquake','India','Earthquake',8964);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_150','2016 Indian heat wave','India','Heat wave',1111);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_151','Hurricane Maria','Puerto Rico','Tropical cyclone',3059);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_152','Hurricane Maria','Dominica','Tropical cyclone',3059);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_153','2018 Sulawesi earthquake and tsunami','Indonesia','Earthquake',4340);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_154','2018 Sulawesi earthquake and tsunami','Indonesia','Tsunami',4340);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_155','2019 European heat waves','Europe','Heat wave',3951);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_156','2020 Indian floods','India','Flood',1922);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_157','2020 Indian floods','Bangladesh','Flood',1922);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_158','2021 Haiti earthquake','Haiti','Earthquake',2248);
INSERT INTO "natural_disasters" ("Event Disaster ID","Event Name","Countries affected","Event Disaster Type","Event Death toll (Estimate)") VALUES ('disaster_159','2022 European heat waves','Europe','Heat wave',12125);
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_1','1917-11-01','1918-01-01','No day or month given, so 01 is a placeholder day.','disaster_1');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_2','1918-02-13',NULL,NULL,'disaster_2');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_3','1918-02-13',NULL,NULL,'disaster_3');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_4','1918-02-13',NULL,NULL,'disaster_4');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_5','1919-09-02','1919-09-16',NULL,'disaster_5');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_6','1920-12-16',NULL,NULL,'disaster_6');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_7','1920-12-16',NULL,NULL,'disaster_7');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_8','1921-09-07','1921-09-11',NULL,'disaster_8');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_9','1922-07-27','1922-08-03',NULL,'disaster_9');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_10','1922-07-27','1922-08-03',NULL,'disaster_10');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_11','1923-09-01',NULL,NULL,'disaster_11');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_12','1924-07-01',NULL,'No day or month given, so 01 is a placeholder day.','disaster_12');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_13','1925-03-16',NULL,NULL,'disaster_13');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_14','1926-10-14','1926-10-28',NULL,'disaster_14');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_15','1926-10-14','1926-10-28',NULL,'disaster_15');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_16','1926-10-14','1926-10-28',NULL,'disaster_16');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_17','1926-10-14','1926-10-28',NULL,'disaster_17');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_18','1927-05-22',NULL,NULL,'disaster_18');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_19','1927-05-22',NULL,NULL,'disaster_19');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_20','1928-09-12','1928-09-21',NULL,'disaster_20');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_21','1928-09-12','1928-09-21',NULL,'disaster_21');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_22','1928-09-12','1928-09-21',NULL,'disaster_22');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_23','1928-09-12','1928-09-21',NULL,'disaster_23');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_24','1928-09-12','1928-09-21',NULL,'disaster_24');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_25','1929-05-01',NULL,NULL,'disaster_25');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_26','1929-05-01',NULL,NULL,'disaster_26');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_27','1930-09-03',NULL,NULL,'disaster_27');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_28','1931-07-01','1391-11-01','No day or month given, so 01 is a placeholder day.','disaster_28');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_29','1932-11-09',NULL,NULL,'disaster_29');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_30','1932-11-09',NULL,NULL,'disaster_30');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_31','1933-08-25',NULL,NULL,'disaster_31');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_32','1934-01-15',NULL,NULL,'disaster_32');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_33','1934-01-15',NULL,NULL,'disaster_33');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_34','1965-05-31',NULL,NULL,'disaster_34');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_35','1936-06-01','1936-09-01','No day or month given, so 01 is a placeholder day.','disaster_35');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_36','1936-06-01','1936-09-01','No day or month given, so 01 is a placeholder day.','disaster_36');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_37','1937-09-02',NULL,NULL,'disaster_37');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_38','1938-07-01',NULL,'No day or month given, so 01 is a placeholder day.','disaster_38');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_39','1939-12-27',NULL,NULL,'disaster_39');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_40','1940-11-10',NULL,NULL,'disaster_40');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_41','1941-01-11',NULL,NULL,'disaster_41');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_42','1942-10-14','1942-10-18',NULL,'disaster_42');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_43','1943-11-27',NULL,NULL,'disaster_43');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_44','1944-01-15',NULL,NULL,'disaster_44');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_45','1945-11-28',NULL,NULL,'disaster_45');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_46','1945-11-28',NULL,NULL,'disaster_46');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_47','1946-08-04',NULL,NULL,'disaster_47');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_48','1947-09-15',NULL,NULL,'disaster_48');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_49','1948-10-06',NULL,NULL,'disaster_49');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_50','1948-10-06',NULL,NULL,'disaster_50');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_51','1949-09-28','1949-10-14',NULL,'disaster_51');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_52','1950-01-01',NULL,'No day or month given, so 01 is a placeholder day.','disaster_52');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_53','1951-09-18',NULL,NULL,'disaster_53');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_54','1952-11-04',NULL,NULL,'disaster_54');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_55','1953-07-01',NULL,'No day or month given, so 01 is a placeholder day.','disaster_55');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_56','1954-06-01','1954-09-01','No day or month given, so 01 is a placeholder day.','disaster_56');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_57','1955-09-22','1955-09-30',NULL,'disaster_57');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_58','1955-09-22','1955-09-30',NULL,'disaster_58');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_59','1956-08-01',NULL,NULL,'disaster_59');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_60','1957-12-13',NULL,NULL,'disaster_60');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_61','1958-09-26',NULL,NULL,'disaster_61');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_62','1959-01-01',NULL,'No day or month given, so 01 is a placeholder day.','disaster_62');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_63','1960-10-31',NULL,NULL,'disaster_63');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_64','1961-05-06','1961-05-09',NULL,'disaster_64');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_65','1962-09-01',NULL,NULL,'disaster_65');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_66','1963-05-28',NULL,NULL,'disaster_66');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_67','1964-11-04','1964-11-11',NULL,'disaster_67');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_68','1965-05-11','1965-05-12',NULL,'disaster_68');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_69','1965-06-01','1965-06-02',NULL,'disaster_69');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_70','1966-08-19',NULL,NULL,'disaster_70');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_71','1966-12-01','1967-01-01','No day or month given, so 01 is a placeholder day.','disaster_71');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_72','1968-08-31',NULL,NULL,'disaster_72');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_73','1969-07-26',NULL,NULL,'disaster_73');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_74','1970-11-03',NULL,NULL,'disaster_74');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_75','1971-08-01',NULL,NULL,'disaster_75');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_76','1972-04-10',NULL,NULL,'disaster_76');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_77','1973-02-06',NULL,NULL,'disaster_77');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_78','1974-09-18','1974-09-20',NULL,'disaster_78');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_79','1974-09-18','1974-09-20',NULL,'disaster_79');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_80','1974-09-18','1974-09-20',NULL,'disaster_80');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_81','1974-09-18','1974-09-20',NULL,'disaster_81');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_82','1974-09-18','1974-09-20',NULL,'disaster_82');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_83','1974-09-18','1974-09-20',NULL,'disaster_83');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_84','1975-08-07',NULL,NULL,'disaster_84');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_85','1976-07-28',NULL,NULL,'disaster_85');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_86','1977-11-19',NULL,NULL,'disaster_86');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_87','1978-09-16',NULL,NULL,'disaster_87');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_88','1979-08-15','1979-09-08',NULL,'disaster_88');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_89','1979-08-15','1979-09-08',NULL,'disaster_89');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_90','1980-10-10',NULL,NULL,'disaster_90');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_91','1981-06-11',NULL,NULL,'disaster_91');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_92','1982-12-13',NULL,NULL,'disaster_92');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_93','1983-10-30',NULL,NULL,'disaster_93');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_94','1984-08-26','1984-09-06',NULL,'disaster_94');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_95','1985-11-14',NULL,NULL,'disaster_95');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_96','1986-08-21',NULL,NULL,'disaster_96');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_97','1987-03-06',NULL,NULL,'disaster_97');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_98','1998-12-07',NULL,NULL,'disaster_98');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_99','1989-07-27',NULL,NULL,'disaster_99');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_100','1990-06-21',NULL,NULL,'disaster_100');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_101','1991-04-24','1991-04-30',NULL,'disaster_101');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_102','1992-12-12',NULL,NULL,'disaster_102');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_103','1992-12-12',NULL,NULL,'disaster_103');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_104','1993-07-30',NULL,NULL,'disaster_104');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_105','1994-06-06',NULL,NULL,'disaster_105');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_106','1995-01-17',NULL,NULL,'disaster_106');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_107','1996-11-04','1997-11-07',NULL,'disaster_107');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_108','1997-11-01','1997-11-09',NULL,'disaster_108');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_109','1997-11-01','1997-11-09',NULL,'disaster_109');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_110','1997-11-01','1997-11-09',NULL,'disaster_110');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_111','1997-11-01','1997-11-09',NULL,'disaster_111');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_112','1998-10-22','1998-11-09',NULL,'disaster_112');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_113','1998-10-22','1998-11-09',NULL,'disaster_113');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_114','1998-10-22','1998-11-09',NULL,'disaster_114');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_115','1998-10-22','1998-11-09',NULL,'disaster_115');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_116','1998-10-22','1998-11-09',NULL,'disaster_116');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_117','1998-10-22','1998-11-09',NULL,'disaster_117');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_118','1999-08-17',NULL,NULL,'disaster_118');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_119','2000-02-01','2000-03-01','No day or month given, so 01 is a placeholder day.','disaster_119');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_120','2001-01-26',NULL,NULL,'disaster_120');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_121','2002-05-01',NULL,'No day or month given, so 01 is a placeholder day.','disaster_121');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_122','2003-07-01','2003-08-01','No day or month given, so 01 is a placeholder day.','disaster_122');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_123','2004-12-26',NULL,NULL,'disaster_123');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_124','2004-12-26',NULL,NULL,'disaster_124');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_125','2004-12-26',NULL,NULL,'disaster_125');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_126','2004-12-26',NULL,NULL,'disaster_126');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_127','2004-12-26',NULL,NULL,'disaster_127');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_128','2004-12-26',NULL,NULL,'disaster_128');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_129','2004-12-26',NULL,NULL,'disaster_129');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_130','2004-12-26',NULL,NULL,'disaster_130');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_131','2004-12-26',NULL,NULL,'disaster_131');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_132','2004-12-26',NULL,NULL,'disaster_132');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_133','2005-10-08',NULL,NULL,'disaster_133');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_134','2005-10-08',NULL,NULL,'disaster_134');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_135','2006-05-26',NULL,NULL,'disaster_135');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_136','2007-11-11','2007-11-16',NULL,'disaster_136');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_137','2007-11-11','2007-11-16',NULL,'disaster_137');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_138','2008-04-27','2008-05-03',NULL,'disaster_138');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_139','2009-09-30',NULL,NULL,'disaster_139');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_140','2010-01-12',NULL,NULL,'disaster_140');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_141','2011-03-11',NULL,NULL,'disaster_141');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_142','2011-03-11',NULL,NULL,'disaster_142');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_143','2012-12-04','2012-12-05',NULL,'disaster_143');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_144','2013-11-08','2013-11-11',NULL,'disaster_144');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_145','2013-11-08','2013-11-11',NULL,'disaster_145');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_146','2013-11-08','2013-11-11',NULL,'disaster_146');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_147','2014-05-02',NULL,NULL,'disaster_147');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_148','2015-04-25',NULL,NULL,'disaster_148');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_149','2015-04-25',NULL,NULL,'disaster_149');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_150','2016-04-01','2016-05-01','No day or month given, so 01 is a placeholder day.','disaster_150');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_151','2017-09-19','2017-09-21',NULL,'disaster_151');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_152','2017-09-19','2017-09-21',NULL,'disaster_152');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_153','2018-09-28',NULL,NULL,'disaster_153');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_154','2018-09-28',NULL,NULL,'disaster_154');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_155','2019-06-01','2019-07-01','No day or month given, so 01 is a placeholder day.','disaster_155');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_156','2016-06-01','2020-09-01','No day or month given, so 01 is a placeholder day.','disaster_156');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_157','2016-06-01','2020-09-01','No day or month given, so 01 is a placeholder day.','disaster_157');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_158','2021-08-14',NULL,NULL,'disaster_158');
INSERT INTO "time" ("time_id","Date (From)","Date (To)","Note","disaster_id") VALUES ('time_159','2022-06-12',NULL,NULL,'disaster_159');
INSERT INTO "top_list_of_natural_disasters" ("Top Event ID","Top Event Death toll (Highest estimate)","Top Event Name","Top Event Location","Top Event Date","Top Event Note","disaster_id") VALUES ('event_1',4000000,'1931 China floods','China','1931-07-01','No day given, so 01 is a placeholder day.','disaster_28');
INSERT INTO "top_list_of_natural_disasters" ("Top Event ID","Top Event Death toll (Highest estimate)","Top Event Name","Top Event Location","Top Event Date","Top Event Note","disaster_id") VALUES ('event_2',2000000,'1887 Yellow River flood','China','1887-09-01','No day given, so 01 is a placeholder day.',NULL);
INSERT INTO "top_list_of_natural_disasters" ("Top Event ID","Top Event Death toll (Highest estimate)","Top Event Name","Top Event Location","Top Event Date","Top Event Note","disaster_id") VALUES ('event_3',830000,'1556 Shaanxi earthquake','China','1556-01-23',NULL,NULL);
INSERT INTO "top_list_of_natural_disasters" ("Top Event ID","Top Event Death toll (Highest estimate)","Top Event Name","Top Event Location","Top Event Date","Top Event Note","disaster_id") VALUES ('event_4',655000,'1976 Tangshan earthquake','China','1976-07-28',NULL,'disaster_85');
INSERT INTO "top_list_of_natural_disasters" ("Top Event ID","Top Event Death toll (Highest estimate)","Top Event Name","Top Event Location","Top Event Date","Top Event Note","disaster_id") VALUES ('event_5',316000,'2010 Haiti earthquake','Haiti','2010-01-12',NULL,'disaster_140');
INSERT INTO "top_list_of_natural_disasters" ("Top Event ID","Top Event Death toll (Highest estimate)","Top Event Name","Top Event Location","Top Event Date","Top Event Note","disaster_id") VALUES ('event_6',300000,'1970 Bhola cyclone','Bangladesh','1970-11-13',NULL,'disaster_74');
INSERT INTO "top_list_of_natural_disasters" ("Top Event ID","Top Event Death toll (Highest estimate)","Top Event Name","Top Event Location","Top Event Date","Top Event Note","disaster_id") VALUES ('event_7',300000,'526 Antioch earthquake','Turkey','0526-05-01','No day given, so 01 is a placeholder day.',NULL);
INSERT INTO "top_list_of_natural_disasters" ("Top Event ID","Top Event Death toll (Highest estimate)","Top Event Name","Top Event Location","Top Event Date","Top Event Note","disaster_id") VALUES ('event_8',300000,'1839 Coringa cyclone','India','1839-11-25',NULL,NULL);
INSERT INTO "top_list_of_natural_disasters" ("Top Event ID","Top Event Death toll (Highest estimate)","Top Event Name","Top Event Location","Top Event Date","Top Event Note","disaster_id") VALUES ('event_9',273400,'1920 Haiyuan earthquake','China','1920-12-16',NULL,'disaster_7');
INSERT INTO "top_list_of_natural_disasters" ("Top Event ID","Top Event Death toll (Highest estimate)","Top Event Name","Top Event Location","Top Event Date","Top Event Note","disaster_id") VALUES ('event_10',229000,'Typhoon Nina','China','1975-08-07',NULL,'disaster_84');
COMMIT;
